package fr.anisekai.scheduler.plan;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Represents a set of instructions generated by the EventScheduler to be executed by a service.
 *
 * @param <ID>
 *         The type of the entity's identifier.
 */
public class SchedulingPlan<ID extends Serializable> {

    private final List<SchedulingAction> actions = new ArrayList<>();

    /**
     * Adds a new action to this plan.
     *
     * @param action
     *         The action to add.
     */
    public void addAction(SchedulingAction action) {

        this.actions.add(action);
    }

    /**
     * Retrieves an unmodifiable list of all actions in this plan.
     *
     * @return The list of actions.
     */
    public List<SchedulingAction> getActions() {

        return Collections.unmodifiableList(this.actions);
    }

}
